image: cenote/jasperstarter-env

pipelines:
  default:
    - step:
        name: Maven build
        caches:
          - maven
        script:
          - mvn clean package -P snapshot
        artifacts:
          - target/*.zip
          - target/site/**
    - step:
        name: Upload artifact to sourceforge downloads
        trigger: manual
        script:
          - ssh-keyscan -t rsa ${SF_HOST} >>  ~/.ssh/known_hosts
          - (umask 077; echo $SF_SSH_BASE64 | base64 --decode > ~/.ssh/id_rsa)
          - scp target/*.zip ${SF_USER}@${SF_HOST}:${SF_FILEBASE}/snapshots/
    - step:
        name: Upload artifact to bitbucket downloads
        trigger: manual
        script:
          - ARTIFACT=$(ls -1 target/*.zip|head -n1)
          - ARTIFACT_BASENAME=$(basename $ARTIFACT)
          - curl -X POST -v --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${ARTIFACT}"

  tags:
    '*-*':
      - step:
          name: Maven release build and upload
          caches:
            - maven
          script:
            #- mvn clean package -P release,windows-setup
            - mvn clean package -P release
            - bash bitbucket-release-to-sourceforge.bash

  branches:
    java7*:
      - step:
          name: Java7 Maven build
          image: maven:3.6-jdk-7
          caches:
            - maven
          script:
            - mvn -B clean package -P snapshot
          artifacts:
            - target/*.zip
            - target/site/**

    java9*:
      - step:
          image: cenote/xenial-java9
          script:
            - mvn -version
            - mvn clean package -P snapshot,windows-setup -Dmaven.test.skip=true
            - mvn test
            # upload new artifact to sourceforge downloads
            - ssh-keyscan -t rsa ${SF_HOST} >>  ~/.ssh/known_hosts
            - (umask 077; echo $SF_SSH_BASE64 | base64 --decode > ~/.ssh/id_rsa)
            - scp target/*.zip ${SF_USER}@${SF_HOST}:${SF_FILEBASE}/snapshots/
            # upload new artifact to bitbucket downloads
            - ARTIFACT=$(ls -1 target/*.zip|head -n1)
            - ARTIFACT_BASENAME=$(basename $ARTIFACT)
            - curl -X POST -v --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${ARTIFACT}"

  custom:
    windows-setup:
      - step:
          name: Windows Setup
          image: cenote/jasperstarter-env
          caches:
            - maven
          script:
            - mvn clean package -P snapshot,windows-setup
        artifacts:
          - target/*.exe

    java10-test:
      - step:
          name: Java10 Test
          image: maven:3.6-jdk-10
          caches:
            - maven
          script:
            - mvn -B clean test
          artifacts:
            - target/**

    java11-test:
      - step:
          name: Java11 Test
          image: maven:3.6-jdk-11
          caches:
            - maven
          script:
            - mvn -B clean test
          artifacts:
            - target/**

    java12-test:
      - step:
          name: Java12 Test
          image: maven:3.6-jdk-12
          caches:
            - maven
          script:
            - mvn -B clean test
          artifacts:
            - target/**
